--This adds 100 random customer, each have been taken from following site: https://1000randomnames.com/. hopefully its random enough :)
--Warning, this will delete all data first in the table, to replace it with new. 
--If you just wish to add 100 serial numbers, comment the first 4 commands.

Delete Customer
Go

DBCC CHECKIDENT (Customer, RESEED, 0);
GO

Insert into Customer(Email, FirstName, LastName) values
('Kimberly@Roberson.test', 'Kimberly', 'Roberson'),
('Shepherd@Blevins.test', 'Shepherd', 'Blevins'),
('Aila@Frank.test', 'Aila', 'Frank'),
('Braylen@Swanson.test', 'Braylen', 'Swanson'),
('Helen@Delgado.test', 'Helen', 'Delgado'),
('Colt@Pruitt.test', 'Colt', 'Pruitt'),
('Brylee@Gardner.test', 'Brylee', 'Gardner'),
('Alan@Gates.test', 'Alan', 'Gates'),
('Melina@Watts.test', 'Melina', 'Watts'),
('Dakota@Cherry.test', 'Dakota', 'Cherry'),
('Nyomi@Franco.test', 'Nyomi', 'Franco'),
('Gage@Underwood.test', 'Gage', 'Underwood'),
('Ensley@Sanchez.test', 'Ensley', 'Sanchez'),
('Joseph@Bullock.test', 'Joseph', 'Bullock'),
('Winnie@Wilkinson.test', 'Winnie', 'Wilkinson'),
('Leonard@Bonilla.test', 'Leonard', 'Bonilla'),
('Romina@Guerrero.test', 'Romina', 'Guerrero'),
('Bryce@Bautista.test', 'Bryce', 'Bautista'),
('Antonella@Manning.test', 'Antonella', 'Manning'),
('Seth@Stanton.test', 'Seth', 'Stanton'),
('Jaycee@Flynn.test', 'Jaycee', 'Flynn'),
('Kannon@Carlson.test', 'Kannon', 'Carlson'),
('Kali@Murray.test', 'Kali', 'Murray'),
('Ashton@Zamora.test', 'Ashton', 'Zamora'),
('Sierra@Martin.test', 'Sierra', 'Martin'),
('Mateo@Estes.test', 'Mateo', 'Estes'),
('Brittany@Stark.test', 'Brittany', 'Stark'),
('Kristopher@McKee.test', 'Kristopher', 'McKee'),
('Kori@Pittman.test', 'Kori', 'Pittman'),
('Valentino@Brewer.test', 'Valentino', 'Brewer'),
('Thea@Arellano.test', 'Thea', 'Arellano'),
('Kellan@Conrad.test', 'Kellan', 'Conrad'),
('Bexley@Montes.test', 'Bexley', 'Montes'),
('Darren@Woodard.test', 'Darren', 'Woodard'),
('Aubrie@Barnes.test', 'Aubrie', 'Barnes'),
('Damian@Anthony.test', 'Damian', 'Anthony'),
('Macy@Freeman.test', 'Macy', 'Freeman'),
('Jayce@Kramer.test', 'Jayce', 'Kramer'),
('Hanna@Hammond.test', 'Hanna', 'Hammond'),
('Francis@Bowen.test', 'Francis', 'Bowen'),
('Dream@Moss.test', 'Dream', 'Moss'),
('Porter@Combs.test', 'Porter', 'Combs'),
('Irene@Hester.test', 'Irene', 'Hester'),
('Rene@Chen.test', 'Rene', 'Chen'),
('Valeria@Bender.test', 'Valeria', 'Bender'),
('Zavier@Stephens.test', 'Zavier', 'Stephens'),
('Millie@Valenzuela.test', 'Millie', 'Valenzuela'),
('Jamari@Gallagher.test', 'Jamari', 'Gallagher'),
('Elliott@Chen.test', 'Elliott', 'Chen'),
('Emmanuel@Cortes.test', 'Emmanuel', 'Cortes'),
('Lea@Richards.test', 'Lea', 'Richards'),
('Holden@Young.test', 'Holden', 'Young'),
('Zoey@Franklin.test', 'Zoey', 'Franklin'),
('Simon@Wagner.test', 'Simon', 'Wagner'),
('Maeve@Garrett.test', 'Maeve', 'Garrett'),
('Kairo@Meyer.test', 'Kairo', 'Meyer'),
('Sara@Winters.test', 'Sara', 'Winters'),
('Deandre@Doyle.test', 'Deandre', 'Doyle'),
('Annalise@Chen.test', 'Annalise', 'Chen'),
('Emmanuel@Townsend.test', 'Emmanuel', 'Townsend'),
('Azalea@Ahmed.test', 'Azalea', 'Ahmed'),
('Harry@Jimenez.test', 'Harry', 'Jimenez'),
('Adeline@Hunt.test', 'Adeline', 'Hunt'),
('Jesus@Chavez.test', 'Jesus', 'Chavez'),
('Nevaeh@Massey.test', 'Nevaeh', 'Massey'),
('Donald@Reese.test', 'Donald', 'Reese'),
('Rosemary@Bailey.test', 'Rosemary', 'Bailey'),
('Axel@Contreras.test', 'Axel', 'Contreras'),
('Daniela@Sharp.test', 'Daniela', 'Sharp'),
('Royce@Calderon.test', 'Royce', 'Calderon'),
('Serena@Michael.test', 'Serena', 'Michael'),
('Bronson@Pruitt.test', 'Bronson', 'Pruitt'),
('Brylee@Hensley.test', 'Brylee', 'Hensley'),
('Layne@Warner.test', 'Layne', 'Warner'),
('Wynter@Colon.test', 'Wynter', 'Colon'),
('Bruce@Browning.test', 'Bruce', 'Browning'),
('Princess@Simmons.test', 'Princess', 'Simmons'),
('Harrison@Brown.test', 'Harrison', 'Brown'),
('Charlotte@Dodson.test', 'Charlotte', 'Dodson'),
('Seven@Duke.test', 'Seven', 'Duke'),
('Melani@Jimenez.test', 'Melani', 'Jimenez'),
('Silas@Vang.test', 'Silas', 'Vang'),
('Madisyn@Hancock.test', 'Madisyn', 'Hancock'),
('Rex@Harrington.test', 'Rex', 'Harrington'),
('Legacy@Lester.test', 'Legacy', 'Lester'),
('Lee@Haynes.test', 'Lee', 'Haynes'),
('Lexi@Esparza.test', 'Lexi', 'Esparza'),
('Carl@Durham.test', 'Carl', 'Durham'),
('Tiffany@Lucas.test', 'Tiffany', 'Lucas'),
('Chance@Landry.test', 'Chance', 'Landry'),
('Brynleigh@Rice.test', 'Brynleigh', 'Rice'),
('Graham@Peters.test', 'Graham', 'Peters'),
('Leila@Spencer.test', 'Leila', 'Spencer'),
('Ace@Ward.test', 'Ace', 'Ward'),
('Ariana@Gregory.test', 'Ariana', 'Gregory'),
('Travis@Beltran.test', 'Travis', 'Beltran'),
('Kaydence@Gray.test', 'Kaydence', 'Gray'),
('Nicholas@Solomon.test', 'Nicholas', 'Solomon'),
('Mylah@Cordova.test', 'Mylah', 'Cordova'),
('Vicente@Henson.test', 'Vicente', 'Henson')


Select * from Customer

